- name:
    en: Family Law
    ru: Семейное Право
  icon: fa-child
  summary:
    en: english
    ru: russian
  description:
    en: english
    ru: |
      - Интернациональный брак - брак с гражданином США, лицами без гражданства, брак ,заключенный на территории США и на территории России ( бывших стран СНГ)
      - Брачный договор – заключение, расторжение, оспаривание, признание недействительным,
      - Расторжение брака
      - Алименты
        - Соглашение об уплате алиментов на несовершеннолетних детей (заключение, расторжение, оспаривание в судебном порядке, признание недействительным)
        - Взыскание алиментов в судебном порядке на несовершеннолетних детей
        - Взыскание дополнительных расходов со второго родителя на несовершеннолетних детей,
        - Взыскание алиментов на нетрудоспособных совершеннолетних детей,
        - Взыскание алиментов  на нетрудоспособного супруга
        - Решение вопросов о взыскании алиментов в рамках исполнительного производства ( взыскание алиментов с должника по решению суда, соглашению об уплате алиментов)
      - Раздел имущества
      -	Соглашение о разделе совместно нажитого имущества (заключение, расторжение, оспаривание в судебном порядке, признание недействительным)
      -	Устаноление отцовства в добровольном порядке и установление судом  факта признания отцовства,
      -	Оспаривание отцоства в судебном порядке
      -	Изменение имени  и фамилиии ребенка,
      -	Определение порядка воспитания ребенка и встреч с ребенком.
      -	Ограничение родительских прав
      - вопросы усыновления,
      - соглашение ( разрешение) о вывозе ребенка за пределы России,


- name:
    en: Real Estate
    ru: Жилищное Право
  icon: fa-home
  summary:
    en: english
    ru: russian
  description:
    en: english
    ru: |
      - Перевод жилого помещения в нежилое,
      - Переустройство, перепланировка жилого помещения,
      - вопросы по договору социального найма
      - перерасчет коммунальных услуг
      - определение порядка пользования жилым помещением
      - определение долей в квартире
      - выкуп доли в квартире,
      - перерасчет платы за жилое помещение и коммунальные услуги, насчитанной Товариществом Собственников Жилья,
      - признание решений собраний собственников жилых помщенеий недействительным.
      - Договоры купли-продажи жилого помещения (квартиры)
      - договоры аренды жилого помещения,
      - оформление доверенностей на право купли-продажи недвижимого имущества,
      - доверенности на право управление земельным участком,
      - регистрация и снятие с регистрационного учета в жилом помещении,
      - договоры дарения жилого помещения, земельного участка,


- name:
    en: Business
    ru: Коммерческое Право
  icon: fa-line-chart
  summary:
    en: english
    ru: russian
  description:
    en: english
    ru: |
      - Юридическое сопровождение при заключении договоров и экспертная оценка  и анализ заключенного договора
      - договоры поставки товаров с России и бывших стран СНГ,
      - транспортные договоры,
      - оспаривание договорных отношений, расторжение договора,признание недействительным
      - взыскание имщественного ущерба, неустойки, пени.


- name:
    en: Wills and Trust
    ru: Наследство
  icon: fa-file-text-o
  summary:
    en: english
    ru: russian
  description:
    en: english
    ru: |
      - составление завещания,
      - наследование по завещанию ( установление обязательной доли в завещательном имуществе, оспаривание завещения, недействительность завещения)
      - наследование по закону,
      - принятие наследства, отказ от наследства,в том числе в пользу третьих лиц,


- name:
    en: Injury
    ru: Возмещение Ущерба
  icon: fa-user-md
  summary:
    en: english
    ru: russian
  description:
    en: english
    ru: |
      - возмещение материального и морального ущерба, причиненного здоровью, (преступлением, на производстве, несчастный случай)
      - Возмещение ущерба, причиненного имуществу,
      - Исполнительное производство
      - взыскание присужденного имущества ( денежных средств, в том числе алиментов ) по решению суда,
      - Подача исполнительного листа в Службу судебных приставов и дальнейшее представление интересов клиента  в Службе Судебных Приставов.


- name:
    en: Criminal
    ru: Уголовное Право
  icon: fa-key
  summary:
    en: english
    ru: russian
  description:
    en: english
    ru: |
      - составление и направление запроса об истребовании сведений судимостях клиента,
      - правовая оценка и анализ дела, как находящегося на стадии возбуждения уголовного дела, рассмотрения  судом, так и на стадии апелляции.
      - составление запросов, жалоб, ходатайств в рамках уголовного дела


- name:
    en: Renewal of Documents
    ru: Восстановление Документов
  icon: fa-files-o
  summary:
    en: english
    ru: russian
  description:
    en: english
    ru: |
      - восстановление документов, выданных в органах ЗАГС
      - свидетельство  расторжении брака,
      - Свидетельство о заключении брака,
      - Свидетельство о рождении,
      - Свидетельство о смерти
      - установлени фактов имеющих юридическое значение,
      - составление запросов и получение справок из Высших учебных заведений (академическая справка), справки из архивов личного дела,


- name:
    en: Power of Attorney
    ru: Доверенности
  icon: fa-institution
  summary:
    en: english
    ru: russian
  description:
    en: english
    ru: |
      - оформление генеральной доверенности,
      - доверенность о распоряжении имуществом,
      - доверенность об истребовании документов ,
      - на представительство в Пенсионном Фонде РФ
      - доверенность на получение пенсии в РФ
      - доверенность на получение пенсии  по почте,
      - заявление о переводе назначенной пенсии за пределы РФ,
      - оформление пенсии
      - заявление об отказе или принятии наследства
      - доверенность на ведение дел о наследстве,
      - доверенности о купле-продаже недвижимого имущества
      - доверенность об управлении и распоряжении недвижимым имуществом без права продажи,
      - оформление пенсии,

- name:
    en: Process
    ru: Процессуалное Право
  icon: fa-refresh
  summary:
    en: english
    ru: russian
  description:
    en: english
    ru: |
      - составление процессуальных документов
      - претензий,
      - исковых заявлений,
      - различного рода ходатайств
      - отзыв,
      - апелляционные жалобы


- name:
    en: Auto
    ru: Правонарушения в области дорожного движения
  icon: fa-car
  summary:
    en: english
    ru: russian
  description:
    en: english
    ru: |
      - ГИБДД (Государственная Инспекция Безопасности Дорожного Движения)
      - представление интересов клинета в органах ГИБДД и сопровождение дела в суде по делам
      - управление транспортным средством при наличии неисправностей или условий, при которых эксплуатация транспортного средста запрещена,
      - превышение установленной скорости движения,
      - проезд на запрещающий сигнал светофора,
      - управление трансопртным средством водителем, находчщимся в состоянии алкогольного или наркотического опьянения.

